<?php
include('auth.php');
require_once('../tcpdf/tcpdf.php'); // Adjust the path if you're not using Composer

// Database connection
$con = new mysqli('localhost', 'root', '', 'archive system 2');

$query = "SELECT thesis.*, thesis_author.Th_Author 
          FROM thesis
          INNER JOIN thesis_author ON thesis.Th_Code = thesis_author.Th_Code";

$run = mysqli_query($con, $query);

// Create new PDF document with legal size paper
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, 'LEGAL', true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Thesis Report');
$pdf->SetSubject('Thesis Report');
$pdf->SetKeywords('TCPDF, PDF, report, thesis');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Thesis Report', 'Generated by BU Online Library');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add content
$html = '<h1>Thesis List</h1>
         <table border="1" cellspacing="3" cellpadding="4">
         <thead>
             <tr>
                 <th>Thesis Code</th>
                 <th>Thesis Title</th>
                 <th>Author Name</th>
                 <th>Course</th>
                 <th>Advisor</th>
                 <th>Category</th>
                 <th>Thematic Area</th>
                 <th>Date Modified</th>
                 <th>Department</th>
             </tr>
         </thead>
         <tbody>';

while ($row = mysqli_fetch_assoc($run)) {
    $html .= '<tr>
                 <td>' . $row['Th_Code'] . '</td>
                 <td>' . $row['Th_Title'] . '</td>
                 <td>' . $row['Th_Author'] . '</td>
                 <td>' . $row['Th_Course'] . '</td>
                 <td>' . $row['Th_Advisor'] . '</td>
                 <td>' . $row['Th_Category'] . '</td>
                 <td>' . $row['Th_ThematicArea'] . '</td>
                 <td>' . $row['Th_DateModified'] . '</td>
                 <td>' . $row['Th_Department'] . '</td>
             </tr>';
}

$html .= '</tbody></table>';

// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('thesis_report.pdf', 'I');

// Close database connection
mysqli_close($con);
?>
